import "@rainbow-me/rainbowkit/styles.css";
import Providers from "./provider";
import { Geist, Geist_Mono } from "next/font/google";
import Background from "../../components/Backgound";
import FloatingSupportButton from "../../components/FloatingButton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <link
          rel="stylesheet"
          href="/globals.css" // Example CDN link
          crossOrigin="anonymous"
        />
      </header>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
